import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
    goalsContainer: {
      flex: 1,
      position: "relative",
    },
    goalsWrapper: {
      padding: 20,
      paddingTop: 16,
    },
    emptyGoalsWrapper: {
      flexGrow: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyStateContainer: {
      alignItems: "center",
      padding: 20,
      paddingTop: 40,
    },
    // New header styles
    emptyStateTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#fff",
      marginBottom: 8,
      textAlign: "center",
      letterSpacing: 0.3,
    },
    emptyStateSubtitle: {
      fontSize: 16,
      color: "#888",
      textAlign: "center",
      lineHeight: 22,
      marginBottom: 20,
      fontWeight: "400",
    },
    // Progress Ring for Behavioral Nudge
    progressRingContainer: {
      alignItems: "center",
      marginBottom: 12,
    },
    progressRingBackground: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 3,
      borderColor: "rgba(74, 144, 226, 0.2)",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
    },
    progressRingFill: {
      position: "absolute",
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 3,
      borderColor: "transparent",
      borderTopColor: "#4A90E2",
      borderRightColor: "#4A90E2",
    },
    progressRingText: {
      fontSize: 10,
      color: "#4A90E2",
      fontWeight: "700",
    },
    progressRingMessage: {
      fontSize: 12,
      color: "#4A90E2",
      textAlign: "center",
      marginBottom: 20,
      fontWeight: "500",
    },
    // Mascot container with glow
    mascotContainer: {
      position: "relative",
      width: 120,
      height: 120,
      marginBottom: 32,
      alignItems: "center",
      justifyContent: "center",
    },
    mascotGlow: {
      position: "absolute",
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: "rgba(74, 144, 226, 0.08)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
      elevation: 5,
    },
    mascotImageContainer: {
      width: 160,
      height: 160,
      marginBottom: 24,
      borderRadius: 80,
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
    },
    emptyStateImage: {
      width: "100%",
      height: "100%",
    },
    // Action Cards Row
    actionCardsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "stretch",
      width: "100%",
      marginBottom: 40,
      gap: 16,
    },
    primaryActionCard: {
      flex: 1,
      backgroundColor: "rgba(74, 144, 226, 0.95)",
      borderRadius: 20,
      padding: 20,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.3)",
      position: "relative",
      overflow: "hidden",
    },
    primaryActionCardGlow: {
      position: "absolute",
      top: -2,
      left: -2,
      right: -2,
      bottom: -2,
      borderRadius: 22,
      backgroundColor: "transparent",
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.6)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.8,
      shadowRadius: 12,
    },
    secondaryActionCard: {
      flex: 1,
      backgroundColor: "rgba(255, 255, 255, 0.05)",
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.2)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 2,
      position: "relative",
      overflow: "hidden",
    },
    tertiaryActionCard: {
      flex: 1,
      backgroundColor: "rgba(32, 178, 170, 0.08)",
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: "rgba(32, 178, 170, 0.25)",
      shadowColor: "#20B2AA",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 2,
      position: "relative",
      overflow: "hidden",
    },
    actionCardContent: {
      alignItems: "center",
      justifyContent: "center",
      minHeight: 100,
      minWidth: 44, // Ensure accessibility tap target
      position: "relative",
      zIndex: 2,
    },
    primaryActionText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "700",
      textAlign: "center",
      marginTop: 12,
      marginBottom: 6,
      letterSpacing: 0.3,
      textShadowColor: "rgba(0, 0, 0, 0.3)",
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
    },
    secondaryActionText: {
      color: "#4A90E2",
      fontSize: 15,
      fontWeight: "700",
      textAlign: "center",
      marginTop: 12,
      marginBottom: 10,
      letterSpacing: 0.3,
    },
    tertiaryActionText: {
      color: "#20B2AA",
      fontSize: 15,
      fontWeight: "700",
      textAlign: "center",
      marginTop: 12,
      letterSpacing: 0.3,
    },
    actionSubtext: {
      color: "rgba(255, 255, 255, 0.9)",
      fontSize: 11,
      textAlign: "center",
      fontWeight: "500",
      letterSpacing: 0.2,
    },
    templateChips: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: 4,
    },
    templateChip: {
      backgroundColor: "rgba(74, 144, 226, 0.2)",
      color: "#4A90E2",
      fontSize: 10,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 8,
      fontWeight: "500",
    },
    templateSuggestion: {
      fontSize: 9,
      color: "#4A90E2",
      textAlign: "center",
      marginTop: 4,
      fontStyle: "italic",
    },
    timelineRow: {
      marginBottom: 12,
      position: "relative",
      paddingLeft: 32,
      paddingVertical: 6,
      paddingRight: 12,
      borderRadius: 12,
      backgroundColor: "transparent",
    },
    selectedTimelineRow: {
      backgroundColor: "rgba(31, 31, 31, 0.8)",
      paddingRight: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    timelineDot: {
      position: "absolute",
      left: 8,
      top: 12,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: "#4A90E2",
      borderWidth: 2,
      borderColor: "#121212",
      zIndex: 2,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    timelineLine: {
      position: "absolute",
      left: 14,
      top: 26,
      width: 2,
      height: "100%",
      backgroundColor: "rgba(74, 144, 226, 0.2)",
    },
    timelineContent: {
      marginLeft: 8,
    },
    timelineHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    timelineIconContainer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(74, 144, 226, 0.1)",
      justifyContent: "center",
      alignItems: "center",
    },
    timelineYear: {
      fontSize: 16,
      fontWeight: "700",
      color: "#4A90E2",
      letterSpacing: 0.5,
    },
    timelineLabel: {
      fontSize: 15,
      color: "#eee",
      marginTop: 4,
      fontWeight: "500",
      letterSpacing: 0.3,
    },
    timelineDescriptionContainer: {
      marginTop: 8,
      padding: 12,
      backgroundColor: "rgba(42, 42, 42, 0.3)",
      borderRadius: 8,
      borderLeftWidth: 2,
      borderLeftColor: "#4A90E2",
    },
    timelineDescription: {
      fontSize: 14,
      color: "#bbb",
      lineHeight: 20,
      letterSpacing: 0.2,
    },
    addGoalButton: {
      position: "absolute",
      bottom: 25,
      right: 20,
      backgroundColor: "black",
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 20,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
    },
    addGoalText: {
      color: "#fff",
      marginLeft: 8,
      fontWeight: "600",
      fontSize: 15,
      letterSpacing: 0.3,
      fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      backgroundColor: "#1f1f1f",
      borderRadius: 20,
      padding: 24,
      width: "100%",
      maxWidth: 400,
      borderWidth: 1,
      borderColor: "#333",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#fff",
      marginBottom: 24,
      textAlign: "center",
    },
    inputContainer: {
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 16,
      color: "#fff",
      marginBottom: 8,
      fontWeight: "600",
    },
    input: {
      backgroundColor: "#2a2a2a",
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      fontSize: 16,
      color: "#fff",
      borderWidth: 1,
      borderColor: "#333",
      marginBottom: 4,
    },
    textArea: {
      minHeight: 80,
      maxHeight: 150,
      paddingTop: 12,
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 24,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      marginHorizontal: 6,
    },
    cancelButton: {
      backgroundColor: "#333",
      borderWidth: 1,
      borderColor: "#444",
    },
    saveButton: {
      backgroundColor: "#4A90E2",
    },
    cancelButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    inputError: {
      color: "#ff6b6b",
      fontSize: 12,
      marginTop: 4,
    },
    datePickerButton: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#2a2a2a",
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: "#333",
    },
    datePickerButtonText: {
      fontSize: 16,
      color: "#fff",
    },
    progressContainer: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    progressBarBackground: {
      flex: 1,
      height: 6,
      backgroundColor: "#2a2a2a",
      borderRadius: 3,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 3,
    },
    progressText: {
      fontSize: 12,
      color: "#aaa",
      fontWeight: "600",
      minWidth: 40,
      textAlign: "right",
    },
    goalAmount: {
      fontSize: 12,
      color: "#4A90E2",
      marginTop: 4,
      fontWeight: "600",
    },
    loadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.2)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
    },
    // Sample Goals Preview
    sampleGoalsContainer: {
      width: "100%",
      marginBottom: 24,
    },
    sampleGoalsTitle: {
      fontSize: 14,
      color: "#666",
      textAlign: "center",
      marginBottom: 16,
      fontWeight: "500",
    },
    sampleGoalCard: {
      backgroundColor: "rgba(255, 255, 255, 0.03)",
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.15)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 3,
      // Glass effect
      backdropFilter: "blur(10px)",
      position: "relative",
      overflow: "hidden",
    },
    sampleGoalCardShine: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 1,
      backgroundColor: "rgba(74, 144, 226, 0.4)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.8,
      shadowRadius: 4,
    },
    sampleGoalHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    sampleGoalIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(74, 144, 226, 0.15)",
      marginRight: 16,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.2)",
    },
    sampleGoalInfo: {
      flex: 1,
    },
    sampleGoalTitlePlaceholder: {
      height: 16,
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 6,
      marginBottom: 8,
      width: "70%",
    },
    sampleGoalAmountPlaceholder: {
      height: 14,
      backgroundColor: "rgba(74, 144, 226, 0.15)",
      borderRadius: 6,
      width: "50%",
    },
    sampleProgressBar: {
      height: 6,
      backgroundColor: "rgba(255, 255, 255, 0.05)",
      borderRadius: 3,
      marginBottom: 12,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.1)",
    },
    sampleProgressFill: {
      height: "100%",
      width: "45%",
      backgroundColor: "rgba(74, 144, 226, 0.4)",
      borderRadius: 3,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
    },
    sampleGoalDate: {
      height: 12,
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderRadius: 4,
      width: "35%",
    },
    // Growth Hook
    growthHook: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: "rgba(74, 144, 226, 0.05)",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.1)",
    },
    growthHookText: {
      fontSize: 12,
      color: "#4A90E2",
      textAlign: "center",
      fontWeight: "500",
    },
  });
  
export { styles };
export default styles;
  