import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
    goalsContainer: {
      flex: 1,
      position: "relative",
    },
    goalsWrapper: {
      padding: 20,
      paddingTop: 16,
    },
    emptyGoalsWrapper: {
      flexGrow: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyStateContainer: {
      alignItems: "center",
      padding: 20,
      paddingTop: 20,
      flex: 1,
      justifyContent: "center",
    },
    emptyHeaderSection: {
      alignItems: "center",
      marginBottom: 48,
      paddingHorizontal: 16,
    },
    emptyIconCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: "rgba(74, 144, 226, 0.12)",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.3)",
    },
    emptyMascotWrap: {
      width: 140,
      height: 140,
      borderRadius: 70,
      overflow: "hidden",
      marginBottom: 16,
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.25)",
      backgroundColor: "rgba(74, 144, 226, 0.08)",
    },
    emptyMascotImage: {
      width: "100%",
      height: "100%",
    },
    // Clean, direct messaging
    emptyStateTitle: {
      fontSize: 28,
      fontWeight: "700",
      color: "#fff",
      marginBottom: 16,
      textAlign: "center",
      letterSpacing: 0.3,
    },
    emptyStateSubtitle: {
      fontSize: 16,
      color: "#aaa",
      textAlign: "center",
      lineHeight: 24,
      fontWeight: "400",
      paddingHorizontal: 20,
    },
    emptyPrimaryButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: "#4A90E2",
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginTop: 8,
    },
    emptyPrimaryButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 14,
      letterSpacing: 0.3,
    },
    emptySecondaryLink: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 14,
      paddingVertical: 6,
      paddingHorizontal: 8,
      borderRadius: 8,
      backgroundColor: "rgba(74, 144, 226, 0.06)",
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.12)",
    },
    emptySecondaryLinkText: {
      color: "#4A90E2",
      fontWeight: "700",
      fontSize: 13,
      letterSpacing: 0.2,
    },
    emptyHint: {
      color: "#666",
      fontSize: 12,
      marginTop: 18,
    },
    // New clean button styles
    primaryActionButton: {
      marginBottom: 16,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 12,
    },
    glassButtonContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
      paddingVertical: 18,
      paddingHorizontal: 32,
      overflow: "hidden",
    },
    gradientButtonContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 20,
      paddingVertical: 18,
      paddingHorizontal: 32,
      overflow: "hidden",
    },
    primaryActionButtonText: {
      color: "#fff",
      fontSize: 18,
      fontWeight: "700",
      marginLeft: 12,
      letterSpacing: 0.3,
      textShadowColor: "rgba(0, 0, 0, 0.3)",
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 3,
    },
    secondaryActionButton: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      marginBottom: 32,
    },
    secondaryActionButtonText: {
      color: "#4A90E2",
      fontSize: 16,
      fontWeight: "600",
      textAlign: "center",
      letterSpacing: 0.2,
      lineHeight: 22,
    },
    // Progress Ring for Behavioral Nudge
    progressRingContainer: {
      alignItems: "center",
      marginBottom: 12,
    },
    progressRingBackground: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 3,
      borderColor: "rgba(74, 144, 226, 0.2)",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
    },
    progressRingFill: {
      position: "absolute",
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 3,
      borderColor: "transparent",
      borderTopColor: "#4A90E2",
      borderRightColor: "#4A90E2",
    },
    progressRingText: {
      fontSize: 10,
      color: "#4A90E2",
      fontWeight: "700",
    },
    progressRingMessage: {
      fontSize: 12,
      color: "#4A90E2",
      textAlign: "center",
      marginBottom: 20,
      fontWeight: "500",
    },
    // Clean mascot container
    mascotContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 40,
    },
    mascotImageContainer: {
      width: 120,
      height: 120,
      borderRadius: 60,
      overflow: "hidden",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.2)",
      backgroundColor: "rgba(74, 144, 226, 0.05)",
    },
    emptyStateImage: {
      width: "80%",
      height: "80%",
    },
    // Action Cards Row - Gen Z focused design with better psychology
    actionCardsRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "stretch",
      width: "100%",
      marginBottom: 32,
      gap: 12,
      paddingHorizontal: 8,
    },
    primaryActionCard: {
      flex: 1,
      maxWidth: 110,
      backgroundColor: "rgba(74, 144, 226, 0.95)",
      borderRadius: 24,
      padding: 18,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 15,
      borderWidth: 2,
      borderColor: "rgba(255, 255, 255, 0.15)",
      position: "relative",
      overflow: "hidden",
      minHeight: 130,
    },
    primaryActionCardGlow: {
      position: "absolute",
      top: -6,
      left: -6,
      right: -6,
      bottom: -6,
      borderRadius: 30,
      backgroundColor: "transparent",
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.6)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.8,
      shadowRadius: 20,
    },
    secondaryActionCard: {
      flex: 1,
      maxWidth: 110,
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderRadius: 20,
      padding: 16,
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.25)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      position: "relative",
      overflow: "hidden",
      minHeight: 130,
    },
    tertiaryActionCard: {
      flex: 1,
      maxWidth: 110,
      backgroundColor: "rgba(32, 178, 170, 0.08)",
      borderRadius: 20,
      padding: 16,
      borderWidth: 2,
      borderColor: "rgba(32, 178, 170, 0.3)",
      shadowColor: "#20B2AA",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      position: "relative",
      overflow: "hidden",
      minHeight: 130,
    },
    actionCardContent: {
      alignItems: "center",
      justifyContent: "center",
      minHeight: 94,
      minWidth: 44,
      position: "relative",
      zIndex: 2,
      flex: 1,
    },
    primaryActionText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "800",
      textAlign: "center",
      marginTop: 12,
      marginBottom: 4,
      letterSpacing: 0.5,
      textShadowColor: "rgba(0, 0, 0, 0.3)",
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 4,
      lineHeight: 18,
    },
    secondaryActionText: {
      color: "#4A90E2",
      fontSize: 13,
      fontWeight: "800",
      textAlign: "center",
      marginTop: 12,
      marginBottom: 6,
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    tertiaryActionText: {
      color: "#20B2AA",
      fontSize: 13,
      fontWeight: "800",
      textAlign: "center",
      marginTop: 12,
      marginBottom: 6,
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    actionSubtext: {
      color: "rgba(255, 255, 255, 0.9)",
      fontSize: 11,
      textAlign: "center",
      fontWeight: "600",
      letterSpacing: 0.3,
      lineHeight: 14,
    },
    templateChips: {
      flexDirection: "column",
      alignItems: "center",
      gap: 2,
      marginTop: 4,
    },
    templateChip: {
      backgroundColor: "rgba(74, 144, 226, 0.25)",
      color: "#4A90E2",
      fontSize: 8,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 8,
      fontWeight: "600",
      textAlign: "center",
      letterSpacing: 0.2,
    },
    templateSuggestion: {
      fontSize: 9,
      color: "#4A90E2",
      textAlign: "center",
      marginTop: 4,
      fontStyle: "italic",
    },
    timelineRow: {
      marginBottom: 12,
      position: "relative",
      paddingLeft: 32,
      paddingVertical: 6,
      paddingRight: 12,
      borderRadius: 12,
      backgroundColor: "transparent",
    },
    selectedTimelineRow: {
      backgroundColor: "rgba(31, 31, 31, 0.8)",
      paddingRight: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    timelineDot: {
      position: "absolute",
      left: 8,
      top: 12,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: "#4A90E2",
      borderWidth: 2,
      borderColor: "#121212",
      zIndex: 2,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    timelineLine: {
      position: "absolute",
      left: 14,
      top: 26,
      width: 2,
      height: "100%",
      backgroundColor: "rgba(74, 144, 226, 0.2)",
    },
    timelineContent: {
      marginLeft: 8,
    },
    timelineHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    timelineIconContainer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(74, 144, 226, 0.1)",
      justifyContent: "center",
      alignItems: "center",
    },
    timelineYear: {
      fontSize: 16,
      fontWeight: "700",
      color: "#4A90E2",
      letterSpacing: 0.5,
    },
    timelineLabel: {
      fontSize: 15,
      color: "#eee",
      marginTop: 4,
      fontWeight: "500",
      letterSpacing: 0.3,
    },
    timelineDescriptionContainer: {
      marginTop: 8,
      padding: 12,
      backgroundColor: "rgba(42, 42, 42, 0.3)",
      borderRadius: 8,
      borderLeftWidth: 2,
      borderLeftColor: "#4A90E2",
    },
    timelineDescription: {
      fontSize: 14,
      color: "#bbb",
      lineHeight: 20,
      letterSpacing: 0.2,
    },
    addGoalButton: {
      position: "absolute",
      bottom: 25,
      right: 20,
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      borderRadius: 25,
      paddingVertical: 12,
      paddingHorizontal: 20,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 8,
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.3)",
      marginBottom: 0,
      paddingBottom: 12,
    },
    addGoalText: {
      color: "#fff",
      marginLeft: 8,
      fontWeight: "600",
      fontSize: 15,
      letterSpacing: 0.3,
      fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      backgroundColor: "#1f1f1f",
      borderRadius: 20,
      padding: 24,
      width: "100%",
      maxWidth: 400,
      borderWidth: 1,
      borderColor: "#333",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#fff",
      marginBottom: 24,
      textAlign: "center",
    },
    inputContainer: {
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 16,
      color: "#fff",
      marginBottom: 8,
      fontWeight: "600",
    },
    input: {
      backgroundColor: "#2a2a2a",
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      fontSize: 16,
      color: "#fff",
      borderWidth: 1,
      borderColor: "#333",
      marginBottom: 4,
    },
    textArea: {
      minHeight: 80,
      maxHeight: 150,
      paddingTop: 12,
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 24,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      marginHorizontal: 6,
    },
    cancelButton: {
      backgroundColor: "#333",
      borderWidth: 1,
      borderColor: "#444",
    },
    saveButton: {
      backgroundColor: "#4A90E2",
    },
    cancelButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    inputError: {
      color: "#ff6b6b",
      fontSize: 12,
      marginTop: 4,
    },
    datePickerButton: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#2a2a2a",
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: "#333",
    },
    datePickerButtonText: {
      fontSize: 16,
      color: "#fff",
    },
    progressContainer: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    progressBarBackground: {
      flex: 1,
      height: 6,
      backgroundColor: "#2a2a2a",
      borderRadius: 3,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 3,
    },
    progressText: {
      fontSize: 12,
      color: "#aaa",
      fontWeight: "600",
      minWidth: 40,
      textAlign: "right",
    },
    goalAmount: {
      fontSize: 12,
      color: "#4A90E2",
      marginTop: 4,
      fontWeight: "600",
    },
    loadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.2)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
    },
    // Sample Goals Preview - Perfectly centered and Gen Z optimized
    sampleGoalsContainer: {
      width: "100%",
      marginBottom: 36,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    sampleGoalsTitle: {
      fontSize: 18,
      color: "#aaa",
      textAlign: "center",
      marginBottom: 20,
      fontWeight: "700",
      letterSpacing: 0.6,
    },
    sampleGoalsStack: {
      position: "relative",
      width: 320,
      height: 150,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
    },
    sampleGoalCard: {
      backgroundColor: "rgba(255, 255, 255, 0.05)",
      borderRadius: 24,
      padding: 20,
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.25)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      elevation: 12,
      position: "absolute",
      width: 300,
      height: 120,
      overflow: "hidden",
      left: 10, // Center the cards
    },
    sampleGoalCardFront: {
      top: 0,
      zIndex: 2,
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderColor: "rgba(74, 144, 226, 0.4)",
      shadowOpacity: 0.3,
      borderWidth: 2,
    },
    sampleGoalCardBack: {
      top: 15,
      left: 20, // Slightly offset for stacking effect
      zIndex: 1,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
      borderColor: "rgba(74, 144, 226, 0.2)",
      opacity: 0.7,
      transform: [{ scale: 0.9 }],
      borderWidth: 1.5,
    },
    sampleGoalCardShine: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 3,
      backgroundColor: "rgba(74, 144, 226, 0.8)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 1,
      shadowRadius: 12,
      borderRadius: 24,
    },
    sampleGoalHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    sampleGoalIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(74, 144, 226, 0.25)",
      marginRight: 16,
      borderWidth: 2,
      borderColor: "rgba(74, 144, 226, 0.4)",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      justifyContent: "center",
      alignItems: "center",
    },
    sampleGoalInfo: {
      flex: 1,
    },
    sampleGoalTitlePlaceholder: {
      height: 16,
      backgroundColor: "rgba(255, 255, 255, 0.12)",
      borderRadius: 8,
      marginBottom: 8,
      width: "75%",
      shadowColor: "rgba(255, 255, 255, 0.1)",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
    },
    sampleGoalAmountPlaceholder: {
      height: 14,
      backgroundColor: "rgba(74, 144, 226, 0.2)",
      borderRadius: 7,
      width: "55%",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
    },
    sampleProgressBar: {
      height: 6,
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 3,
      marginBottom: 10,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "rgba(74, 144, 226, 0.15)",
      shadowColor: "rgba(0, 0, 0, 0.2)",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
    },
    sampleProgressFill: {
      height: "100%",
      width: "50%",
      backgroundColor: "rgba(74, 144, 226, 0.6)",
      borderRadius: 3,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
    },
    sampleGoalDate: {
      height: 12,
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 6,
      width: "40%",
      shadowColor: "rgba(255, 255, 255, 0.1)",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
    },
    // Footer Note
    footerNote: {
      fontSize: 14,
      color: "#888",
      textAlign: "center",
      fontWeight: "500",
      paddingHorizontal: 32,
      lineHeight: 20,
    },
    // Tip text under preview
    gettingStartedTip: {
      fontSize: 12,
      color: "#aaa",
      textAlign: "center",
      marginTop: 10,
      letterSpacing: 0.2,
    },
    // Sample goal real content
    sampleGoalTitleText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "800",
      marginBottom: 6,
      letterSpacing: 0.4,
    },
    sampleGoalAmountText: {
      color: "#4A90E2",
      fontSize: 13,
      fontWeight: "700",
    },
    sampleGoalMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 10,
    },
    sampleGoalDueText: {
      color: "#bbb",
      fontSize: 12,
      fontWeight: "700",
    },
    // Growth Hook
    growthHook: {
      paddingVertical: 14,
      paddingHorizontal: 20,
      backgroundColor: "rgba(74, 144, 226, 0.08)",
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: "rgba(74, 144, 226, 0.2)",
      marginBottom: 24,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    growthHookText: {
      fontSize: 13,
      color: "#4A90E2",
      textAlign: "center",
      fontWeight: "600",
      letterSpacing: 0.3,
    },
  });
  
export { styles };
export default styles;
  