import { StyleSheet, Platform } from "react-native";

// Font size constants for consistency
const FONTS = {
  xs: 10,
  sm: 13,
  base: 14,
  lg: 17,
  xl: 20,
  xxl: 24,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#121212",
  },
  container: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 20,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 8 : 16,
    paddingBottom: 12,
    backgroundColor: "#121212",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  headerIconContainer: {
    backgroundColor: "rgba(74, 144, 226, 0.1)",
    padding: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.2)",
  },
  headerTextContainer: {
    flex: 1,
    marginLeft: 12,
  },
  greetingText: {
    fontSize: FONTS.lg,
    marginBottom: 2,
    fontWeight: "600",
    color: "#fff",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  subGreeting: {
    fontSize: FONTS.sm,
    color: "rgba(255, 255, 255, 0.6)",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    letterSpacing: 0.2,
  },
  title: {
    fontSize: FONTS.xxl,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 12,
    marginTop: 12,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  netWorthCard: {
    backgroundColor: "#1f1f1f",
    borderRadius: 16,
    paddingVertical: 20,
    marginBottom: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    paddingHorizontal: 20,
    width: "100%",
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.1)",
  },
  netWorthText: {
    fontSize: 28,
    fontWeight: "700",
    color: "#fff",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    marginBottom: 8,
  },
  netWorthLabel: {
    fontSize: 12,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    marginBottom: 6,
  },
  netWorthTrend: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginTop: 2,
  },
  netWorthTrendText: {
    color: "#4ECDC4",
    fontSize: FONTS.xs,
    fontWeight: "600",
    marginLeft: 4,
    letterSpacing: 0.5,
  },
  netWorthBreakdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginTop: 8,
  },
  breakdownItem: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 4,
    minWidth: 80,
  },
  breakdownLabel: {
    fontSize: 11,
    color: "#aaa",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  breakdownValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
  breakdownIcon: {
    marginBottom: 6,
  },
  breakdownDivider: {
    width: 1,
    height: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginHorizontal: 4,
  },
  insightCard: {
    backgroundColor: "#1e1e1e",
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
  },
  insightTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 6,
  },
  insightText: {
    fontSize: 14,
    color: "#ccc",
  },
  insightSubText: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 40,
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#1f1f1f",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.15)",
    minHeight: 120,
  },
  cardTitle: {
    fontSize: 13,
    color: "#888",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  cardAmount: {
    fontSize: 20,
    fontWeight: "700",
    color: "#fff",
    textAlign: "center",
  },
  addAccountButton: {
    marginTop: 24,
    paddingVertical: 14,
    backgroundColor: "#1f1f1f",
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.3)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addAccountButtonText: {
    color: "#4A90E2",
    fontWeight: "600",
    fontSize: FONTS.sm,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    letterSpacing: 0.3,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(18, 18, 18, 0.8)",
    paddingVertical: 10,
    alignItems: "center",
    zIndex: 1000,
  },
  loadingText: {
    marginTop: 10,
    color: '#fff',
    fontSize: 16,
  },
  primaryBtn: {
    backgroundColor: "#4A90E2",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    marginTop: 24,
  },
  primaryBtnText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  securityNote: {
    marginTop: 12,
    color: "#888",
    fontSize: 12,
    textAlign: "center",
  },
  disconnectButton: {
    padding: 8,
  },
  dropdownArrow: {
    marginLeft: 8,
  },
  disconnectedContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#121212",
  },
  disconnectedContent: {
    alignItems: "center",
    backgroundColor: "#1f1f1f",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    shadowColor: "#4A90E2",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.2)",
  },
  disconnectedTitle: {
    fontSize: FONTS.xl,
    fontWeight: "bold",
    color: "#fff",
    marginTop: 16,
    marginBottom: 8,
    textAlign: "center",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  disconnectedDescription: {
    fontSize: FONTS.base,
    color: "#aaa",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  connectButton: {
    backgroundColor: "#4A90E2",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: "100%",
    alignItems: "center",
  },
  connectButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  gradientBackground: {
    flex: 1,
    backgroundColor: "#1A1A2E",
  },
  updateBanner: {
    backgroundColor: "#FFA500",
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  updateBannerText: {
    color: "#000",
    fontSize: FONTS.base,
    fontWeight: "600",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  finnyMessageContainer: {
    marginBottom: 24,
    marginTop: 8,
  },
  finnyMessage: {
    borderRadius: 16,
    padding: 18,
    backgroundColor: "#1f1f1f",
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.1)",
  },
  finnyMessageContent: {
    flex: 1,
    marginLeft: 12,
  },
  finnyMessageTitle: {
    color: "#4A90E2",
    fontSize: FONTS.xs,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  finnyMessageText: {
    color: "#fff",
    fontSize: FONTS.base,
    fontWeight: "500",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    letterSpacing: 0.3,
  },
  finnyIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    // backgroundColor: "rgba(74, 144, 226, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  goalsSection: {
    marginBottom: 24,
  },
  goalsSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  goalsTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: {
    fontSize: FONTS.lg,
    fontWeight: "700",
    color: "#4A90E2",
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    paddingHorizontal: 5,
  },
  viewAllButton: {
    backgroundColor: "#1f1f1f",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.3)",
  },
  viewAllText: {
    color: "#4A90E2",
    fontSize: FONTS.sm,
    fontWeight: "500",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  goalCard: {
    marginTop: 4,
    backgroundColor: "#1f1f1f",
    borderRadius: 16,
    padding: 18,
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.15)",
  },
  goalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  goalTitle: {
    fontSize: FONTS.base,
    fontWeight: "700",
    color: "#fff",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
    letterSpacing: 0.3,
  },
  goalAmount: {
    fontSize: FONTS.base,
    color: "#4A90E2",
    fontWeight: "700",
    fontFamily: Platform.OS === "ios" ? "System" : "sans-serif",
  },
  progressBarBackground: {
    height: 6,
    width: "100%",
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 0,
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: "#4ECDC4",
  },
  goalPercentContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 12,
    alignSelf: 'flex-end',
    gap: 4,
  },
  section: {
    marginBottom: 24,
    paddingHorizontal: 4,
    marginTop: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 8,
    paddingHorizontal: 8,
    backgroundColor: "rgba(74, 144, 226, 0.03)",
    paddingTop: 8,
    borderRadius: 10,
  },
  sectionContent: {
    marginTop: 8,
  },
  itemText: {
    fontSize: 14,
    color: "#ccc",
    paddingVertical: 4,
  },
  cardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 4,
  },
  accountCard: {
    width: "48%",
    marginBottom: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  cardContent: {
    flex: 1,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  cardIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(74, 144, 226, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  cardInfo: {
    flex: 1,
  },
  cardName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 2,
  },
  cardType: {
    fontSize: 11,
    color: "#aaa",
    textTransform: "capitalize",
  },
  cardBalance: {
    fontSize: 15,
    fontWeight: "600",
    color: "#4A90E2",
    marginTop: 4,
  },
  emptyGoalsContainer: {
    backgroundColor: "#1f1f1f",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.1)",
    marginTop: 8,
  },
  emptyGoalsContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  emptyGoalsImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: "hidden",
    // backgroundColor: "rgba(74, 144, 226, 0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyGoalsImage: {
    width: "100%",
    height: "100%",
  },
  emptyGoalsTextContainer: {
    flex: 1,
  },
  emptyGoalsTitle: {
    fontSize: FONTS.base,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 4,
  },
  emptyGoalsDescription: {
    fontSize: FONTS.sm,
    color: "#888",
    marginBottom: 12,
    lineHeight: 18,
  },
  addFirstGoalButton: {
    borderRadius: 17,
    alignSelf: "flex-start",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.3)",
  },
  addFirstGoalContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
    gap: 8,
  },
  addFirstGoalText: {
    color: "#fff",
    fontSize: FONTS.sm,
    fontWeight: "600",
    textShadowColor: "rgba(74, 144, 226, 0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  carouselSlide: {
    paddingVertical: 0,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  spendingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 8,
  },
  spendingColumn: {
    flex: 1,
    alignItems: "center",
  },
  spendingLabel: {
    fontSize: 11,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 8,
    textAlign: "center",
  },
  spendingAmount: {
    fontSize: 24,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 8,
  },
  spendingDivider: {
    width: 1,
    height: 80,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginHorizontal: 20,
  },
  spendingTrend: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(78, 205, 196, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  carouselDots: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 13,
    paddingTop: 10
  },
  carouselDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  carouselDotActive: {
    backgroundColor: "#4A90E2",
    width: 20,
  },
});

export default styles;