import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#121212",
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    backgroundColor: "transparent",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(74, 144, 226, 0.1)",
    position: 'relative',
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: Platform.OS === "ios" ? 100 : 120,
    zIndex: -1,
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  mascotContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    padding: 2,
    borderWidth: 1.5,
    borderColor: "rgba(74, 144, 226, 0.3)",
    overflow: 'hidden',
    marginRight: 12,
    shadowColor: "#4A90E2",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  mascotImage: {
    width: '100%',
    height: '100%',
    borderRadius: 22,
  },
  sparkleContainer: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  sparkleTopRight: {
    top: -8,
    right: -8,
  },
  sparkleTopLeft: {
    top: -6,
    left: -6,
  },
  sparkleBottomRight: {
    bottom: -6,
    right: -6,
  },
  sparkleBottomLeft: {
    bottom: -8,
    left: -8,
  },
  headerContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.7)",
    letterSpacing: 0.3,
    fontWeight: "500",
  },
  clearButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "rgba(255, 59, 48, 0.1)",
    padding: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 59, 48, 0.25)",
    shadowColor: "#FF3B30",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  clearButtonText: {
    color: "#FF3B30",
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 4,
    letterSpacing: 0.2,
  },
  tabSwitcher: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#1c1c1c",
    borderRadius: 12,
    marginHorizontal: 20,
    marginBottom: 10,
  },
  tabButton: {
    paddingVertical: 10,
    flex: 1,
    alignItems: "center",
    borderRadius: 12,
  },
  activeTab: {
    backgroundColor: "#2e2e2e",
  },
  tabText: {
    color: "#aaa",
    fontSize: 14,
  },
  activeText: {
    color: "#4A90E2",
    fontWeight: "600",
  },
  chatArea: {
    flex: 1,
    backgroundColor: "#121212",
  },
  chatContainer: {
    flex: 1,
    paddingBottom: 100,
  },
  chatScroll: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 12,
  },
  chatBubble: {
    maxWidth: "80%",
    padding: 12,
    borderRadius: 18,
    marginVertical: 6,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  chatLeft: {
    alignSelf: "flex-start",
    backgroundColor: "#2c2c2c",
    borderTopLeftRadius: 4,
  },
  chatRight: {
    alignSelf: "flex-end",
    backgroundColor: "#4A90E2",
    borderTopRightRadius: 4,
  },
  chatText: {
    color: "#fff",
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  chatMoney: {
    fontWeight: "600",
    color: "#4A90E2",
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 8,
    paddingRight: 8,
    backgroundColor: "#1f1f1f",
    borderRadius: 24,
    paddingBottom: 8,
    marginHorizontal: 10,
    marginBottom: 0,
    borderWidth: 1.5,
    borderColor: "rgba(74, 144, 226, 0.25)",
    paddingTop: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  plusButton: {
    
    padding: 2,
    marginRight: 4,
  },
  sendButton: {
    // backgroundColor: "#4A90E2",
    // width: 35,
    // height: 35,
    // borderRadius: 17.5,
    // justifyContent: "center",
    // alignItems: "center",
    // marginLeft: 10,
  },
  input: {
    flex: 1,
    fontSize: 14,
    color: "#fff",
    paddingVertical: 4,
    marginHorizontal: 4,
  },
  nudgeContainer: {
    marginBottom: 16,
    paddingHorizontal: 10,
  },
  nudgeHeaderText: {
    color: "#888",
    fontSize: 13,
    marginBottom: 8,
    marginLeft: 2,
    fontWeight: "500",
    textAlign: "center",
  },
  nudgeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  nudgeBox: {
    backgroundColor: "#2a2a2a",
    borderRadius: 10,
    padding: 6,
    marginBottom: 8,
    width: "48%",
    shadowColor: "#4A90E2",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.2)",
  },
  nudgeText: {
    color: "#fff",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 16,
  },
  typingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 8,
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4A90E2",
    marginHorizontal: 2,
  },
  inputBarContainer: {
    position: 'absolute',
    bottom: -5,
    left: 0,
    right: 0,
    backgroundColor: "#121212",
    paddingTop: 2,
    paddingBottom: Platform.OS === "ios" ? 20 : 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(44, 44, 44, 0.8)",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 5,
  },
  suggestionsContainer: {
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 6,
    marginTop: 2,
    // Optionally add backdrop blur here if using a BlurView wrapper in the component
  },
  suggestionChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    marginRight: 8,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    opacity: 0.95,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.25)",
    backgroundColor: "rgba(26, 61, 102, 0.35)", // glassy blue
    // If BlurView is used, backgroundColor can be more transparent
  },
  suggestionIcon: {
    marginRight: 5,
  },
  suggestionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#FFFFFF",
    letterSpacing: 0.2,
  },
  scrollToBottomButton: {
    position: 'absolute',
    right: 16,
    bottom: 160,
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  scrollButtonTouchable: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollButtonGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
  },
}); 