import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#121212",
  },
  container: {
    flex: 1,
    backgroundColor: "#121212",
    padding: 20,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 10,
    backgroundColor: "#121212",
  },
  headerTextContainer: {
    flex: 1,
    marginLeft: 16,
  },
  greetingText: {
    fontSize: 18,
    marginBottom: 2,
    fontWeight: "600",
    color: "#fff",
  },
  subGreeting: {
    fontSize: 16,
    // fontWeight: "600",
    color: "#aaa",
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 16,
  },
  netWorthCard: {
    backgroundColor: "#1f1f1f",
    borderRadius: 16,
    paddingVertical: 24,
    marginBottom: 24,
    alignItems: "center",
    shadowColor: "#4A90E2",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: "rgba(74, 144, 226, 0.2)",
    paddingHorizontal: 20,
    width: "100%",
  },
  netWorthText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#4A90E2",
    marginBottom: 20,
  },
  netWorthBreakdown: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginTop: 8,
  },
  breakdownItem: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 4,
    minWidth: 80,
  },
  breakdownLabel: {
    fontSize: 11,
    color: "#aaa",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  breakdownValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
  breakdownIcon: {
    marginBottom: 6,
  },
  breakdownDivider: {
    width: 1,
    height: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginHorizontal: 4,
  },
  insightCard: {
    backgroundColor: "#1e1e1e",
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
  },
  insightTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 6,
  },
  insightText: {
    fontSize: 14,
    color: "#ccc",
  },
  insightSubText: {
    fontSize: 13,
    color: "#888",
    marginTop: 2,
  },
  goalsSection: {
    marginBottom: 24,
  },
  goalCard: {
    marginTop: 10,
    backgroundColor: "#1e1e1e",
    borderRadius: 12,
    paddingTop: 16,
    borderLeftWidth: 4,
    paddingHorizontal: 16,
    borderLeftColor: "#4A90E2",
    paddingBottom: 10
  },
  goalTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#eee",
    marginBottom: 8,
  },
  progressBarBackground: {
    height: 8,
    width: "100%",
    backgroundColor: "#333",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#4A90E2",
  },
  goalPercent: {
    fontSize: 12,
    color: "#aaa",
    marginTop: 6,
    textAlign: "right",
  },
  section: {
    marginBottom: 20,
    backgroundColor: "#1e1e1e",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#eee",
  },
  sectionContent: {
    marginTop: 12,
  },
  itemText: {
    fontSize: 14,
    color: "#ccc",
    paddingVertical: 4,
  },
  cardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  accountCard: {
    backgroundColor: "#2a2a2a",
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    width: "48%",
    // borderLeftWidth: 4,
    // borderLeftColor: "#4A90E2",
    overflow: "hidden",
  },
  cardContent: {
    padding: 12,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  cardIconContainer: {
    backgroundColor: "rgba(74, 144, 226, 0.2)",
    padding: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  cardInfo: {
    flexShrink: 1,
  },
  cardName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 2,
  },
  cardType: {
    fontSize: 12,
    color: "#aaa",
    textTransform: "capitalize",
  },
  cardFooter: {
    marginTop: 8,
  },
  cardBalance: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#4A90E2",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#999",
    marginTop: 10,
    fontSize: 14,
  },
  primaryBtn: {
    backgroundColor: "#4A90E2",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    marginTop: 24,
  },
  primaryBtnText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  securityNote: {
    marginTop: 12,
    color: "#888",
    fontSize: 12,
    textAlign: "center",
  },
  disconnectButton: {
    marginLeft: "auto",
    padding: 8,
  },
  dropdownArrow: {
    marginLeft: 8,
  },
});
