import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
    timelineContainer: {
      flex: 1,
      position: "relative",
    },
    timelineWrapper: {
      padding: 20,
      paddingTop: 16,
    },
    timelineRow: {
      marginBottom: 12,
      position: "relative",
      paddingLeft: 32,
      paddingVertical: 6,
      paddingRight: 12,
      borderRadius: 12,
      backgroundColor: "transparent",
    },
    selectedTimelineRow: {
      backgroundColor: "rgba(31, 31, 31, 0.8)",
      paddingRight: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    timelineDot: {
      position: "absolute",
      left: 8,
      top: 12,
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: "#4A90E2",
      borderWidth: 2,
      borderColor: "#121212",
      zIndex: 2,
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    timelineLine: {
      position: "absolute",
      left: 14,
      top: 26,
      width: 2,
      height: "100%",
      backgroundColor: "rgba(74, 144, 226, 0.2)",
    },
    timelineContent: {
      marginLeft: 8,
    },
    timelineHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    timelineIconContainer: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "rgba(74, 144, 226, 0.1)",
      justifyContent: "center",
      alignItems: "center",
    },
    timelineYear: {
      fontSize: 16,
      fontWeight: "700",
      color: "#4A90E2",
      letterSpacing: 0.5,
    },
    timelineLabel: {
      fontSize: 15,
      color: "#eee",
      marginTop: 4,
      fontWeight: "500",
      letterSpacing: 0.3,
    },
    timelineDescriptionContainer: {
      marginTop: 8,
      padding: 12,
      backgroundColor: "rgba(42, 42, 42, 0.3)",
      borderRadius: 8,
      borderLeftWidth: 2,
      borderLeftColor: "#4A90E2",
    },
    timelineDescription: {
      fontSize: 14,
      color: "#bbb",
      lineHeight: 20,
      letterSpacing: 0.2,
    },
    addGoalButton: {
      position: "absolute",
      bottom: 25,
      right: 20,
      backgroundColor: "black",
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 20,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#4A90E2",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
    },
    addGoalText: {
      color: "#fff",
      marginLeft: 8,
      fontWeight: "600",
      fontSize: 15,
      letterSpacing: 0.3,
      fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      backgroundColor: "#1f1f1f",
      borderRadius: 20,
      padding: 24,
      width: "100%",
      maxWidth: 400,
      borderWidth: 1,
      borderColor: "#333",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#fff",
      marginBottom: 24,
      textAlign: "center",
    },
    inputContainer: {
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 16,
      color: "#fff",
      marginBottom: 8,
      fontWeight: "600",
    },
    input: {
      backgroundColor: "#2a2a2a",
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      fontSize: 16,
      color: "#fff",
      borderWidth: 1,
      borderColor: "#333",
      marginBottom: 4,
    },
    textArea: {
      minHeight: 80,
      maxHeight: 150,
      paddingTop: 12,
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 24,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      marginHorizontal: 6,
    },
    cancelButton: {
      backgroundColor: "#333",
      borderWidth: 1,
      borderColor: "#444",
    },
    saveButton: {
      backgroundColor: "#4A90E2",
    },
    cancelButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    saveButtonText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 16,
    },
    inputError: {
      color: "#ff6b6b",
      fontSize: 12,
      marginTop: 4,
    },
    datePickerButton: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#2a2a2a",
      borderRadius: 8,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: "#333",
    },
    datePickerButtonText: {
      fontSize: 16,
      color: "#fff",
    },
    progressContainer: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    progressBarBackground: {
      flex: 1,
      height: 6,
      backgroundColor: "#2a2a2a",
      borderRadius: 3,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 3,
    },
    progressText: {
      fontSize: 12,
      color: "#aaa",
      fontWeight: "600",
      minWidth: 40,
      textAlign: "right",
    },
    loadingOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.2)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
    },
  });
  
export { styles };
export default styles;
  